/*
 * Text.java
 *
 * Created on 16/05/2010, 10:49:07 PM
 */

package Auxiliar;

import GUI.PanelDibujo;
import java.awt.GraphicsEnvironment;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author fires
 */
public class Text extends javax.swing.JDialog {

     // Obtenemos la referencia al entorno de ventanas
    private GraphicsEnvironment gEnv;

    // Variables
    private String tipoFuentePredeterminada = "Dialog";
    private String texto;
    private PanelDibujo pantallaDibujo;


    /** Creates new form Text */
    public Text() {
        super();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e){}
        gEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        initComponents();
        texto = "";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTextPanel = new javax.swing.JPanel();
        jLabelIntroduzcaTexto = new javax.swing.JLabel();
        jTextFieldTexto = new javax.swing.JTextField();
        jPanelOpcionesTexto = new javax.swing.JPanel();
        jLabelTipolFuente = new javax.swing.JLabel();
        jComboBoxTipoFuentes = new javax.swing.JComboBox(gEnv.getAvailableFontFamilyNames());
        jLabelEstilo = new javax.swing.JLabel();
        jComboBoxTipoEstilo = new javax.swing.JComboBox();
        jLabelTamañoTexto = new javax.swing.JLabel();
        jSpinnerTamañoTexto = new javax.swing.JSpinner(new SpinnerNumberModel(12, 6, 24, 1));
        jPanelConfirmacion = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Texto");

        jLabelIntroduzcaTexto.setText("Introduzca un texto:");

        javax.swing.GroupLayout jPanelTextPanelLayout = new javax.swing.GroupLayout(jPanelTextPanel);
        jPanelTextPanel.setLayout(jPanelTextPanelLayout);
        jPanelTextPanelLayout.setHorizontalGroup(
            jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIntroduzcaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelTextPanelLayout.setVerticalGroup(
            jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIntroduzcaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextFieldTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabelTipolFuente.setText("Fuentes:");
        jLabelTipolFuente.setToolTipText("Tipo de Fuentes");

        jComboBoxTipoFuentes.setMaximumRowCount(5);
        jComboBoxTipoFuentes.setSelectedItem(tipoFuentePredeterminada);
        jComboBoxTipoFuentes.setToolTipText("Tipos de Fuente");
        jComboBoxTipoFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoFuentesActionPerformed(evt);
            }
        });

        jLabelEstilo.setText("Estilo:");

        jComboBoxTipoEstilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Negrita", "Cursiva", "Negrita Cursiva" }));
        jComboBoxTipoEstilo.setToolTipText("Tipo de Estilos");

        jLabelTamañoTexto.setText("Tamaño:");

        jSpinnerTamañoTexto.setToolTipText("Tamaño");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfirmacionLayout = new javax.swing.GroupLayout(jPanelConfirmacion);
        jPanelConfirmacion.setLayout(jPanelConfirmacionLayout);
        jPanelConfirmacionLayout.setHorizontalGroup(
            jPanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmacionLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButtonAceptar)
                .addGap(31, 31, 31)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanelConfirmacionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAceptar, jButtonCancelar});

        jPanelConfirmacionLayout.setVerticalGroup(
            jPanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfirmacionLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar))
                .addContainerGap())
        );

        jPanelConfirmacionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAceptar, jButtonCancelar});

        javax.swing.GroupLayout jPanelOpcionesTextoLayout = new javax.swing.GroupLayout(jPanelOpcionesTexto);
        jPanelOpcionesTexto.setLayout(jPanelOpcionesTextoLayout);
        jPanelOpcionesTextoLayout.setHorizontalGroup(
            jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipolFuente)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxTipoFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabelEstilo)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxTipoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabelTamañoTexto)
                .addGap(5, 5, 5)
                .addComponent(jSpinnerTamañoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jPanelConfirmacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelOpcionesTextoLayout.setVerticalGroup(
            jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                .addGroup(jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTipolFuente))
                    .addComponent(jComboBoxTipoFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelEstilo))
                    .addComponent(jComboBoxTipoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTamañoTexto))
                    .addComponent(jSpinnerTamañoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOpcionesTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOpcionesTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoFuentesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxTipoFuentesActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
	dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        pantallaDibujo = new PanelDibujo();
//        pantallaDibujo.setTipoFuente(jComboBoxTipoFuentes.getSelectedIndex());
    //    pantallaDibujo.setEstiloFuente(jComboBoxTipoEstilo.getSelectedIndex());
        //pantallaDibujo.setTamañoFuente(jSpinnerTamañoTexto.);
        System.out.println("3- paso");
        this.setTexto(jTextFieldTexto.getText());
      //  pantallaDibujo.setTexto(this.getTexto());
        pantallaDibujo.setDrawMode(72);
        this.setVisible(false);
        repaint();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }


    

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Text dialog = new Text();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxTipoEstilo;
    private javax.swing.JComboBox jComboBoxTipoFuentes;
    private javax.swing.JLabel jLabelEstilo;
    private javax.swing.JLabel jLabelIntroduzcaTexto;
    private javax.swing.JLabel jLabelTamañoTexto;
    private javax.swing.JLabel jLabelTipolFuente;
    private javax.swing.JPanel jPanelConfirmacion;
    private javax.swing.JPanel jPanelOpcionesTexto;
    private javax.swing.JPanel jPanelTextPanel;
    private javax.swing.JSpinner jSpinnerTamañoTexto;
    private javax.swing.JTextField jTextFieldTexto;
    // End of variables declaration//GEN-END:variables

}
