/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proyectosbeta
 */
public class VentanaTablaRegistro extends javax.swing.JFrame {
    // Objetos.
    private static String rutaImagenTemporal;
    private static String[] nombreColumnas;
    private static ArrayList listaNombreColumnas;
    private static ResultSet resultSetRegistros;
    private DefaultTableModel modelo;
    private JScrollPane scrollPane;
    
    
    /**
     * Creates new form VentanaTablaRegistro
     */
    public VentanaTablaRegistro(String rutaImagenTemporal, ArrayList listaNombreColumnas, 
            ResultSet resultSetRegistros) {
        /*
         * Los valores de los parametros se guardan en variables de clase,
         * porque lueg se los va a usar.
         */
        this.rutaImagenTemporal = rutaImagenTemporal;
        this.listaNombreColumnas = listaNombreColumnas;
        this.resultSetRegistros = resultSetRegistros;
        
        initComponents();

        /*
         * Instancia del scrollPane.
         */
        scrollPane = new JScrollPane();
        
        /*
         * Se agrega al scrollPane la tabla.
         */
        //scrollPane.add(jTableSeleccionarDatos);
        
        /*
         * En este array se cargan las columnas que viene de la listaNombreColumnas.
         */
        this.nombreColumnas = cargarColumnas();
        
        /* 
         * Se crea una instancia del modelo con las nombre de las columnas
         * que se le pasa al constructor.
         */ 
        modelo = new DefaultTableModel(nombreColumnas, nombreColumnas.length - 1);
        
        // Se agrega filas al modelo.
        agregarFilas();
                
        /*
         * Se coloca el modelo a la tabla.
         */
        jTableSeleccionarDatos.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSeleccionarDatos = new javax.swing.JTable();
        jButtonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSeleccionarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSeleccionarDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSiguiente)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // Ir a la ventanaCrearTexto.
        VentanaCrearTexto ventanaCrearTexto = new VentanaCrearTexto(rutaImagenTemporal);
        ventanaCrearTexto.setLocationRelativeTo(this);
	ventanaCrearTexto.setVisible(true);
        
        // Se cierra la VentanaTablaRegistro.
        this.dispose();
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTablaRegistro(rutaImagenTemporal, listaNombreColumnas, 
                    resultSetRegistros).setVisible(true);
            }
        });
    }
     
    /**
     * 
     */
    private String[] cargarColumnas(){
        String[] nombreColumnas = new String[listaNombreColumnas.size()];
        
        for(int i = 0; i < listaNombreColumnas.size(); i++){
            nombreColumnas[i] = (String)listaNombreColumnas.get(i);
        }
        return nombreColumnas;
    }
    
    /**
     * 
     */
    private void agregarFilas(){
        // Objetos.
        Object datos[] = new Object[nombreColumnas.length]; //Numero de columnas de la tabla

        try {
            while (resultSetRegistros.next()) {
                for (int i = 0; i < nombreColumnas.length; i++) {
                    datos[i] = resultSetRegistros.getObject(i + 1);
	        }
                System.out.println("entro!!!");
	        this.modelo.addRow(datos);
	    }
	}catch(Exception e) {
        }finally{
            if(resultSetRegistros != null){
                try{
                    // Se cierra el ResultSet (resultSetRegistros).
                    resultSetRegistros.close();
                    
                    System.out.println("Se cierra el ResultSet de las tablas!!!");
                }catch(SQLException ex){ 
                     Logger.getLogger(VentanaBaseDatos.class.getName()).log(Level.SEVERE, null, ex);
                }catch(Exception ex){  
                     Logger.getLogger(VentanaBaseDatos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSeleccionarDatos;
    // End of variables declaration//GEN-END:variables
}
