/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author proyectosbeta
 */
/**
 * Clase Ventana donde sale el login a la base de datos.
 * Puede ser dinamica o estatica.
 */
public class VentanaLoginBaseDatos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaLoginBaseDatos
     */
    public VentanaLoginBaseDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarObjetos();
    }
    
     /**
     * Metodo que inicializa los objetos.
     */
    private void inicializarObjetos(){
        // Colocamos el nuevo tipo de layout que queremos que tenga nuestro JDialog.
        this.setLayout(new FlowLayout());
        
        // Agregamos el jPanelLoginBaseDatos con un layout al centro.
        this.add(jPanelLoginBaseDatos, BorderLayout.CENTER);
        
        // Hacemos que el JDialog tenga el tamaño de todos sus elementos.
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginBaseDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenhia = new javax.swing.JLabel();
        jFormattedTextFieldUsuarioLogin = new javax.swing.JFormattedTextField();
        jPasswordFieldContrasenhiaLogin = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Conectarse a la base de datos");

        jLabelUsuario.setText("Usuario:");

        jLabelContrasenhia.setText("Contraseña:");

        jButtonLogin.setText("Login");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginBaseDatosLayout = new javax.swing.GroupLayout(jPanelLoginBaseDatos);
        jPanelLoginBaseDatos.setLayout(jPanelLoginBaseDatosLayout);
        jPanelLoginBaseDatosLayout.setHorizontalGroup(
            jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBaseDatosLayout.createSequentialGroup()
                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginBaseDatosLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanelLoginBaseDatosLayout.createSequentialGroup()
                                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsuario)
                                    .addComponent(jLabelContrasenhia))
                                .addGap(10, 10, 10)
                                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldContrasenhiaLogin)
                                    .addComponent(jFormattedTextFieldUsuarioLogin)))))
                    .addGroup(jPanelLoginBaseDatosLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanelLoginBaseDatosLayout.setVerticalGroup(
            jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBaseDatosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jFormattedTextFieldUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasenhia)
                    .addComponent(jPasswordFieldContrasenhiaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginBaseDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonCancelar))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLoginBaseDatos);
        jPanelLoginBaseDatos.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Se cierra la VentanaLoginBaseDatos.
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * Donde despliega el login de la base de datos.
     *
     * @since 1.6
     */
    public void mostraLoginBaseDatos(){
        // Hace visbile la VentanaLoginBaseDatos.
        this.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLoginBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaLoginBaseDatos dialog = new VentanaLoginBaseDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JFormattedTextField jFormattedTextFieldUsuarioLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContrasenhia;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelLoginBaseDatos;
    private javax.swing.JPasswordField jPasswordFieldContrasenhiaLogin;
    // End of variables declaration//GEN-END:variables
}
