/*
 * GUI_principal.java
 *
 * Created on 17/03/2010, 09:39:02 PM
 */

package GUI;

import Auxiliar.Constantes;
import Figuras.Figura;
import javax.swing.JDialog;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;
import javax.swing.UIManager;

/**
 *
 * @author fires
 */
public class GUI_principal extends javax.swing.JFrame {
    // Objetos
    private PanelDibujo pantallaDibujo;
    private JDialog ventanaAyuda;                           // Ventana Ayuda

    // Obtenemos la referencia al entorno de ventanas
    private GraphicsEnvironment gEnv;

    // Obtenemos el dispositivo gráfico 
    private GraphicsDevice  gd;

    // Cursor Predeterminado
    private Cursor cursorPredeterminado;

    // Cursor Actual
    private Cursor cursorActual;
   
    // Una linkedList para guadar todas las figuras que se crean
    LinkedList<Figura> listaDeFigurasADibujar;

    /** java.awt.event.*
     */
    /** tk
     */
    /** This is a Toolkit value that is initialize by the function
     * getDefaultToolkit().
     */
    Toolkit toolKit;

     /** java.awt.event.*
     */
    /** pencilImg
     */
    /** This is an Image value that is initialize by getImage(), for cursor.
     */
    Image pencilImg;

    /** java.awt.event.*
     */
    /** eraserImg
     */
    /** This is an Image value that is initialize by getImage(), for cursor.
     */

     Image eraserImg;

     /** java.awt.event.*
     */
    /** brushImg
     */
    /** This is an Image value that is initialize by getImage(), for cursor.
     */

     Image brushImg;

     /*
      * El icono de la aplicacion
      *
      */
     Image iconoAplicacion;

    // Variables
    boolean colorObjeto = false;
    String tipoFuentePredeterminada = "Dialog";

    
    /** Creates new form GUI_principal */
    public GUI_principal() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e){
            e.printStackTrace();
        }
        gEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();

        // Obtenemos el dispositivo gráfico primario (por defecto)
        gd = gEnv.getDefaultScreenDevice();
        
        initComponents();
        pantallaDibujo = new PanelDibujo();
        this.setLocationRelativeTo(null);               // centrar el jframe en la pantalla
        pantallaDibujo.setBounds(Constantes.MARGEN_LARGO_PANTALLA_DIBUJO,
                Constantes.MARGEN_ANCHO_PANTALLA_DIBUJO,
                Constantes.MAXIMO_LARGO_PANTALLA_DIBUJO,
                Constantes.MAXIMO_ANCHO_PANTALLA_DIBUJO);     // Dimensiones
        getContentPane().add(pantallaDibujo, java.awt.BorderLayout.CENTER);
        this.add(pantallaDibujo);
        jPanelOpcionesObjeto.setVisible(false);
        pantallaDibujo.setDrawMode(6);   // Mano alzada por defecto
        jLabelHerramientaSeleccionadaObjeto.setText("Mano Alzada");
        jDialogColor.setSize(100, 100);
        jDialogColor.setLocationRelativeTo(this);
        this.setExtendedState(GUI_principal.NORMAL);
        toolKit = Toolkit.getDefaultToolkit();
        iconoAplicacion = toolKit.getImage(getClass().getResource("/imagenes/iconos/paintEvolution.png"));
        this.setIconImage(iconoAplicacion);
        pencilImg = toolKit.getImage(getClass().getResource("/imagenes/cursores/pencil.gif"));
        eraserImg = toolKit.getImage(getClass().getResource("/imagenes/cursores/eraserSmall.gif"));
        brushImg = toolKit.getImage(getClass().getResource("/imagenes/cursores/brush.gif"));
        cursorPredeterminado =  toolKit.createCustomCursor(pencilImg, new Point(10,24),"Pencil Cursor");
        cursorActual = cursorPredeterminado;
        pantallaDibujo.setCursorActual(cursorActual);
        jButtonDesactivarPantallaCompleta.setVisible(false);
        listaDeFigurasADibujar = new LinkedList<Figura>();
        jButtonDesactivarPantallaCompleta.setVisible(false);        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogColor = new javax.swing.JDialog();
        jColorChooserColores = new javax.swing.JColorChooser();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        buttonGroupObjetos = new javax.swing.ButtonGroup();
        jPanelAccesoDirecto = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonDeshacer = new javax.swing.JButton();
        jButtonRehacer = new javax.swing.JButton();
        jButtonZoomIn = new javax.swing.JButton();
        jButtonZoomOut = new javax.swing.JButton();
        jButtonPantallaCompleta = new javax.swing.JButton();
        jButtonDesactivarPantallaCompleta = new javax.swing.JButton();
        jPanelInformacionExtra = new javax.swing.JPanel();
        jLabelCoordenadasPuntero = new javax.swing.JLabel();
        jLabelHerramientaSeleccionada = new javax.swing.JLabel();
        jLabelHerramientaSeleccionadaObjeto = new javax.swing.JLabel();
        jPanelBarraHerramientasTotal = new javax.swing.JPanel();
        jPanelBarraDeHerramientas = new javax.swing.JPanel();
        jToggleButtonLapiz = new javax.swing.JToggleButton();
        jToggleButtonPincel = new javax.swing.JToggleButton();
        jToggleButtonLinea = new javax.swing.JToggleButton();
        jToggleButtonOvalo = new javax.swing.JToggleButton();
        jToggleButtonRectangulo = new javax.swing.JToggleButton();
        jToggleButtonCírculo = new javax.swing.JToggleButton();
        jToggleButtonrectanguloRedondo = new javax.swing.JToggleButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jToggleButtonBorrarIndividual = new javax.swing.JToggleButton();
        jToggleButtonTexto = new javax.swing.JToggleButton();
        jButtonBorrarTodo = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonColorDeFondoPantalla = new javax.swing.JToggleButton();
        jToggleButtonColorObjetos = new javax.swing.JToggleButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        chkRelleno = new javax.swing.JCheckBox();
        jToolBarBarraDeHerramientas = new javax.swing.JToolBar(JToolBar.HORIZONTAL);
        jPanelOpcionesObjeto = new javax.swing.JPanel();
        jLabelTamañoGrosor = new javax.swing.JLabel();
        jComboBoxGrosorBorde = new javax.swing.JComboBox();
        jPanelDerechoVacio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemGuardarComo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemImprimir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemDeshacer = new javax.swing.JMenuItem();
        jMenuItemRehacer = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemZoomIn = new javax.swing.JMenuItem();
        jMenuItemZoomOut = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemIndice = new javax.swing.JMenuItem();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        jDialogColor.setTitle("Colores");
        jDialogColor.setMinimumSize(new java.awt.Dimension(450, 450));
        jDialogColor.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogColorLayout = new javax.swing.GroupLayout(jDialogColor.getContentPane());
        jDialogColor.getContentPane().setLayout(jDialogColorLayout);
        jDialogColorLayout.setHorizontalGroup(
            jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColorLayout.createSequentialGroup()
                .addGroup(jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorChooserColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogColorLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogColorLayout.setVerticalGroup(
            jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogColorLayout.createSequentialGroup()
                .addComponent(jColorChooserColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Evolution v.1.0");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanelAccesoDirecto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/documentoNuevo_32px.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setToolTipText("Nuevo");
        jButtonNuevo.setBorderPainted(false);
        jButtonNuevo.setFocusable(false);
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setMaximumSize(new java.awt.Dimension(71, 59));
        jButtonNuevo.setMinimumSize(new java.awt.Dimension(71, 59));
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(71, 59));
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonNuevo);

        jButtonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/documentoAbrir_32px.png"))); // NOI18N
        jButtonAbrir.setText("Abrir");
        jButtonAbrir.setToolTipText("Abrir");
        jButtonAbrir.setBorderPainted(false);
        jButtonAbrir.setFocusable(false);
        jButtonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbrir.setMaximumSize(new java.awt.Dimension(71, 59));
        jButtonAbrir.setMinimumSize(new java.awt.Dimension(71, 59));
        jButtonAbrir.setPreferredSize(new java.awt.Dimension(71, 59));
        jButtonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonAbrir);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/guardar_32px.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonGuardar);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/impresora_32px.png"))); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setToolTipText("Imprimir");
        jButtonImprimir.setFocusable(false);
        jButtonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimir.setMaximumSize(new java.awt.Dimension(71, 59));
        jButtonImprimir.setMinimumSize(new java.awt.Dimension(71, 59));
        jButtonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonImprimir);

        jButtonDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/desHacer_32px.png"))); // NOI18N
        jButtonDeshacer.setText("Deshacer");
        jButtonDeshacer.setToolTipText("Deshacer");
        jButtonDeshacer.setFocusable(false);
        jButtonDeshacer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeshacer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeshacerActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonDeshacer);

        jButtonRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/reHacer_32px.png"))); // NOI18N
        jButtonRehacer.setText("Rehacer");
        jButtonRehacer.setToolTipText("Rehacer");
        jButtonRehacer.setFocusable(false);
        jButtonRehacer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRehacer.setMaximumSize(new java.awt.Dimension(77, 59));
        jButtonRehacer.setMinimumSize(new java.awt.Dimension(77, 59));
        jButtonRehacer.setPreferredSize(new java.awt.Dimension(77, 59));
        jButtonRehacer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRehacerActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonRehacer);

        jButtonZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/zoom_in_32px.png"))); // NOI18N
        jButtonZoomIn.setText("Zoom In");
        jButtonZoomIn.setToolTipText("Zoom In");
        jButtonZoomIn.setBorderPainted(false);
        jButtonZoomIn.setFocusable(false);
        jButtonZoomIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZoomIn.setMaximumSize(new java.awt.Dimension(77, 59));
        jButtonZoomIn.setMinimumSize(new java.awt.Dimension(77, 59));
        jButtonZoomIn.setPreferredSize(new java.awt.Dimension(77, 59));
        jButtonZoomIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZoomInActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonZoomIn);

        jButtonZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/zoom_out_32px.png"))); // NOI18N
        jButtonZoomOut.setText("Zoom Out");
        jButtonZoomOut.setToolTipText("Zoom Out");
        jButtonZoomOut.setBorderPainted(false);
        jButtonZoomOut.setFocusable(false);
        jButtonZoomOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZoomOut.setPreferredSize(new java.awt.Dimension(79, 59));
        jButtonZoomOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZoomOutActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonZoomOut);

        jButtonPantallaCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/pantallaCompleta_32px.png"))); // NOI18N
        jButtonPantallaCompleta.setText("Pantalla Completa");
        jButtonPantallaCompleta.setToolTipText("Activar Pantalla Completa");
        jButtonPantallaCompleta.setFocusable(false);
        jButtonPantallaCompleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPantallaCompleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPantallaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPantallaCompletaActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonPantallaCompleta);

        jButtonDesactivarPantallaCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/AccesosDirectos/DesactivarPantallaCompleta_32px.png"))); // NOI18N
        jButtonDesactivarPantallaCompleta.setText("Desactivar Pantalla Completa");
        jButtonDesactivarPantallaCompleta.setToolTipText("Desactivar Pantalla Completa");
        jButtonDesactivarPantallaCompleta.setFocusable(false);
        jButtonDesactivarPantallaCompleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDesactivarPantallaCompleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDesactivarPantallaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesactivarPantallaCompletaActionPerformed(evt);
            }
        });
        jPanelAccesoDirecto.add(jButtonDesactivarPantallaCompleta);

        getContentPane().add(jPanelAccesoDirecto, java.awt.BorderLayout.NORTH);

        jPanelInformacionExtra.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanelInformacionExtra.add(jLabelCoordenadasPuntero);

        jLabelHerramientaSeleccionada.setText("Herramienta Seleccionada: ");
        jPanelInformacionExtra.add(jLabelHerramientaSeleccionada);
        jPanelInformacionExtra.add(jLabelHerramientaSeleccionadaObjeto);

        getContentPane().add(jPanelInformacionExtra, java.awt.BorderLayout.SOUTH);

        jPanelBarraDeHerramientas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanelBarraDeHerramientas.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanelBarraDeHerramientas.setLayout(new javax.swing.BoxLayout(jPanelBarraDeHerramientas, javax.swing.BoxLayout.Y_AXIS));

        buttonGroupObjetos.add(jToggleButtonLapiz);
        jToggleButtonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/pencil.png"))); // NOI18N
        jToggleButtonLapiz.setSelected(true);
        jToggleButtonLapiz.setToolTipText("Lápiz");
        jToggleButtonLapiz.setFocusable(false);
        jToggleButtonLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLapizActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonLapiz);

        buttonGroupObjetos.add(jToggleButtonPincel);
        jToggleButtonPincel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/brush_16_16.gif"))); // NOI18N
        jToggleButtonPincel.setToolTipText("Pincel");
        jToggleButtonPincel.setBorderPainted(false);
        jToggleButtonPincel.setFocusable(false);
        jToggleButtonPincel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonPincel.setPreferredSize(new java.awt.Dimension(29, 29));
        jToggleButtonPincel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonPincel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPincelActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonPincel);

        buttonGroupObjetos.add(jToggleButtonLinea);
        jToggleButtonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/linea.png"))); // NOI18N
        jToggleButtonLinea.setToolTipText("Dibujar línea");
        jToggleButtonLinea.setBorderPainted(false);
        jToggleButtonLinea.setFocusable(false);
        jToggleButtonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLineaActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonLinea);

        buttonGroupObjetos.add(jToggleButtonOvalo);
        jToggleButtonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/ellipse.png"))); // NOI18N
        jToggleButtonOvalo.setToolTipText("Dibujar un Óvalo");
        jToggleButtonOvalo.setBorderPainted(false);
        jToggleButtonOvalo.setFocusable(false);
        jToggleButtonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonOvalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOvaloActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonOvalo);

        buttonGroupObjetos.add(jToggleButtonRectangulo);
        jToggleButtonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/rectangulo.png"))); // NOI18N
        jToggleButtonRectangulo.setToolTipText("Dibujar un Rectángulo");
        jToggleButtonRectangulo.setBorderPainted(false);
        jToggleButtonRectangulo.setFocusable(false);
        jToggleButtonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRectanguloActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonRectangulo);

        buttonGroupObjetos.add(jToggleButtonCírculo);
        jToggleButtonCírculo.setText("Círculo");
        jToggleButtonCírculo.setToolTipText("Dibujar un Círculo");
        jToggleButtonCírculo.setBorderPainted(false);
        jToggleButtonCírculo.setFocusable(false);
        jToggleButtonCírculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCírculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCírculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCírculoActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonCírculo);

        buttonGroupObjetos.add(jToggleButtonrectanguloRedondo);
        jToggleButtonrectanguloRedondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/14_roundrect.png"))); // NOI18N
        jToggleButtonrectanguloRedondo.setToolTipText("Dibujar un Rectángulo Redondeado");
        jToggleButtonrectanguloRedondo.setBorderPainted(false);
        jToggleButtonrectanguloRedondo.setFocusable(false);
        jToggleButtonrectanguloRedondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonrectanguloRedondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelBarraDeHerramientas.add(jToggleButtonrectanguloRedondo);
        jPanelBarraDeHerramientas.add(jSeparator7);

        buttonGroupObjetos.add(jToggleButtonBorrarIndividual);
        jToggleButtonBorrarIndividual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/eraser_16_16.gif"))); // NOI18N
        jToggleButtonBorrarIndividual.setToolTipText("Borrador");
        jToggleButtonBorrarIndividual.setBorderPainted(false);
        jToggleButtonBorrarIndividual.setFocusable(false);
        jToggleButtonBorrarIndividual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonBorrarIndividual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonBorrarIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBorrarIndividualActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonBorrarIndividual);

        buttonGroupObjetos.add(jToggleButtonTexto);
        jToggleButtonTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/texto_16px.png"))); // NOI18N
        jToggleButtonTexto.setToolTipText("Texto");
        jToggleButtonTexto.setBorderPainted(false);
        jToggleButtonTexto.setFocusable(false);
        jToggleButtonTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonTexto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTextoActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonTexto);

        buttonGroupObjetos.add(jButtonBorrarTodo);
        jButtonBorrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/BarraHerramientas/eraser.png"))); // NOI18N
        jButtonBorrarTodo.setToolTipText("Borrar Todo");
        jButtonBorrarTodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBorrarTodo.setBorderPainted(false);
        jButtonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodoActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jButtonBorrarTodo);
        jPanelBarraDeHerramientas.add(jSeparator4);

        buttonGroupObjetos.add(jButtonColorDeFondoPantalla);
        jButtonColorDeFondoPantalla.setText("Fondo");
        jButtonColorDeFondoPantalla.setToolTipText("Cambiar de color a la mesa de trabajo");
        jButtonColorDeFondoPantalla.setBorderPainted(false);
        jButtonColorDeFondoPantalla.setFocusable(false);
        jButtonColorDeFondoPantalla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonColorDeFondoPantalla.setMaximumSize(new java.awt.Dimension(50, 21));
        jButtonColorDeFondoPantalla.setMinimumSize(new java.awt.Dimension(50, 21));
        jButtonColorDeFondoPantalla.setPreferredSize(new java.awt.Dimension(50, 21));
        jButtonColorDeFondoPantalla.setRequestFocusEnabled(false);
        jButtonColorDeFondoPantalla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonColorDeFondoPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorDeFondoPantallaActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jButtonColorDeFondoPantalla);

        buttonGroupObjetos.add(jToggleButtonColorObjetos);
        jToggleButtonColorObjetos.setText("ColorObjetos");
        jToggleButtonColorObjetos.setToolTipText("Color de los Objetos");
        jToggleButtonColorObjetos.setBorderPainted(false);
        jToggleButtonColorObjetos.setFocusable(false);
        jToggleButtonColorObjetos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonColorObjetos.setMaximumSize(new java.awt.Dimension(90, 21));
        jToggleButtonColorObjetos.setMinimumSize(new java.awt.Dimension(90, 21));
        jToggleButtonColorObjetos.setPreferredSize(new java.awt.Dimension(85, 21));
        jToggleButtonColorObjetos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonColorObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonColorObjetosActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(jToggleButtonColorObjetos);
        jPanelBarraDeHerramientas.add(jSeparator10);

        chkRelleno.setText("Rellenar");
        chkRelleno.setEnabled(false);
        chkRelleno.setFocusable(false);
        chkRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chkRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRellenoActionPerformed(evt);
            }
        });
        jPanelBarraDeHerramientas.add(chkRelleno);

        jToolBarBarraDeHerramientas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jToolBarBarraDeHerramientas.setRollover(true);
        jToolBarBarraDeHerramientas.setToolTipText("Barra de Herramientas");
        jToolBarBarraDeHerramientas.setBorderPainted(false);
        jPanelBarraDeHerramientas.add(jToolBarBarraDeHerramientas);

        jLabelTamañoGrosor.setText("Grosor:");

        jComboBoxGrosorBorde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxGrosorBorde.setToolTipText("Grosor");
        jComboBoxGrosorBorde.setPreferredSize(new java.awt.Dimension(45, 22));
        jComboBoxGrosorBorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrosorBordeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesObjetoLayout = new javax.swing.GroupLayout(jPanelOpcionesObjeto);
        jPanelOpcionesObjeto.setLayout(jPanelOpcionesObjetoLayout);
        jPanelOpcionesObjetoLayout.setHorizontalGroup(
            jPanelOpcionesObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesObjetoLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabelTamañoGrosor)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxGrosorBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelOpcionesObjetoLayout.setVerticalGroup(
            jPanelOpcionesObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesObjetoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelTamañoGrosor))
            .addGroup(jPanelOpcionesObjetoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jComboBoxGrosorBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelBarraHerramientasTotalLayout = new javax.swing.GroupLayout(jPanelBarraHerramientasTotal);
        jPanelBarraHerramientasTotal.setLayout(jPanelBarraHerramientasTotalLayout);
        jPanelBarraHerramientasTotalLayout.setHorizontalGroup(
            jPanelBarraHerramientasTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBarraDeHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelBarraHerramientasTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBarraHerramientasTotalLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(jPanelOpcionesObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        jPanelBarraHerramientasTotalLayout.setVerticalGroup(
            jPanelBarraHerramientasTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBarraDeHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelBarraHerramientasTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBarraHerramientasTotalLayout.createSequentialGroup()
                    .addGap(0, 287, Short.MAX_VALUE)
                    .addComponent(jPanelOpcionesObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 287, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelBarraHerramientasTotal, java.awt.BorderLayout.WEST);

        jPanelDerechoVacio.setLayout(new javax.swing.BoxLayout(jPanelDerechoVacio, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jPanelDerechoVacio, java.awt.BorderLayout.EAST);

        jMenuArchivo.setMnemonic('A');
        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setToolTipText("Archivo");

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/documentoNuevo_16px.png"))); // NOI18N
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.setToolTipText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/documentoAbrir_16px.png"))); // NOI18N
        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.setToolTipText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAbrir);

        jMenuItemCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/cerrar_16px.png"))); // NOI18N
        jMenuItemCerrar.setText("Cerrar");
        jMenuItemCerrar.setToolTipText("Cerrar");
        jMenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCerrar);
        jMenuArchivo.add(jSeparator2);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/guardar_16px.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.setToolTipText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemGuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/guardarComo_16px.png"))); // NOI18N
        jMenuItemGuardarComo.setText("Guardar Como");
        jMenuItemGuardarComo.setToolTipText("Guardar Como");
        jMenuItemGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarComoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardarComo);
        jMenuArchivo.add(jSeparator3);

        jMenuItemImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/impresora_16px.png"))); // NOI18N
        jMenuItemImprimir.setText("Imprimir");
        jMenuItemImprimir.setToolTipText("Imprimir");
        jMenuItemImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImprimirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemImprimir);
        jMenuArchivo.add(jSeparator1);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.setToolTipText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuEditar.setMnemonic('E');
        jMenuEditar.setText("Editar");
        jMenuEditar.setToolTipText("Editar");

        jMenuItemDeshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/desHacer_16px.png"))); // NOI18N
        jMenuItemDeshacer.setText("Deshacer");
        jMenuItemDeshacer.setToolTipText("Deshacer");
        jMenuItemDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeshacerActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemDeshacer);

        jMenuItemRehacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/reHacer_16px.png"))); // NOI18N
        jMenuItemRehacer.setText("Rehacer");
        jMenuItemRehacer.setToolTipText("Rehacer");
        jMenuItemRehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRehacerActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemRehacer);
        jMenuEditar.add(jSeparator8);

        jMenuItemZoomIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/zoom_in_16px.png"))); // NOI18N
        jMenuItemZoomIn.setText("Zoom In");
        jMenuItemZoomIn.setToolTipText("Zoom In");
        jMenuItemZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZoomInActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemZoomIn);

        jMenuItemZoomOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/zoom_out_16px.png"))); // NOI18N
        jMenuItemZoomOut.setText("Zoom Out");
        jMenuItemZoomOut.setToolTipText("Zoom Out");
        jMenuItemZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZoomOutActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemZoomOut);

        jMenuBar1.add(jMenuEditar);

        jMenuAyuda.setMnemonic('H');
        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.setToolTipText("Ayuda");

        jMenuItemIndice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/ayuda_16px.png"))); // NOI18N
        jMenuItemIndice.setToolTipText("Índice");
        jMenuItemIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIndiceActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemIndice);

        jMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/Menus/acercaDe_16px.png"))); // NOI18N
        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.setToolTipText("Acerca de");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        String codigoHTML = "<html><body><p><b>&nbsp;&nbsp;&nbsp;&nbsp;Autor:</b> " +
                "José González von Schmeling<br><b>&nbsp;&nbsp;&nbsp;&nbsp;Mail:</b> " +
                "josego85@gmail.com<br><b>&nbsp;&nbsp;&nbsp;&nbsp;Año:</b> 2010" +
                "<br><b>&nbsp;&nbsp;&nbsp;&nbsp;Paint Evolution v.1.0</b></body></html>";
        /*JOptionPane.showMessageDialog(this,"Autor: José González von " +
                "Schmeling\nMail: josego85@gmail.com\nAño: 2010\nPaint Evolution v.1.0",
                ConstantesDePaintEvolution.TITULO_PROGRAMA,
                JOptionPane.PLAIN_MESSAGE);*/
        JOptionPane.showMessageDialog(this, codigoHTML,
                Constantes.TITULO_PROGRAMA,
                JOptionPane.PLAIN_MESSAGE);
        pantallaDibujo.repaint();

    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIndiceActionPerformed
        mostrarVentanaAyuda();
    }//GEN-LAST:event_jMenuItemIndiceActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
       pantallaDibujo.abrirImagen();
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        pantallaDibujo.abrirImagen();
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        pantallaDibujo.guardarImagen();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        pantallaDibujo.guardarImagen();
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        pantallaDibujo.borrarTodo();
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarActionPerformed
        pantallaDibujo.borrarTodo();
        pantallaDibujo.setDrawMode(6);      // Trazo a mano alzada
	pantallaDibujo.setColorFondoPantallaDibujo(Color.WHITE);
	pantallaDibujo.setColorSeleccion(Color.BLACK);
	pantallaDibujo.repaint();
    }//GEN-LAST:event_jMenuItemCerrarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        pantallaDibujo.borrarTodo();
        pantallaDibujo.setDrawMode(6);      // Trazo a mano alzada
	pantallaDibujo.setColorFondoPantallaDibujo(Color.WHITE);
	pantallaDibujo.setColorSeleccion(Color.BLACK);
	pantallaDibujo.repaint();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jMenuItemGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarComoActionPerformed
        pantallaDibujo.guardarComoImagen();
    }//GEN-LAST:event_jMenuItemGuardarComoActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(colorObjeto){
            pantallaDibujo.setColorSeleccion(jColorChooserColores.getColor());
        }else{
            pantallaDibujo.setColorFondoPantallaDibujo(jColorChooserColores.getColor());
            pantallaDibujo.repaint();
        }
        jDialogColor.setVisible(false);
        //pantallaDibujo.repaint();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jDialogColor.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jToggleButtonLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLapizActionPerformed
        Cursor pencilCursor = toolKit.createCustomCursor(pencilImg, new Point(10,24),"Pencil Cursor");
	cursorActual = pencilCursor;
        pantallaDibujo.setCursorActual(cursorActual);
        pantallaDibujo.setTamañoBorde(1);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(false);
        jPanelOpcionesObjeto.setVisible(false);
    }//GEN-LAST:event_jToggleButtonLapizActionPerformed

    private void jToggleButtonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLineaActionPerformed
        cursorActual = new Cursor(Cursor.CROSSHAIR_CURSOR);
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(false);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonLineaActionPerformed

    private void jToggleButtonOvaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOvaloActionPerformed
        cursorActual = new Cursor(Cursor.CROSSHAIR_CURSOR);
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(true);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonOvaloActionPerformed

    private void jButtonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodoActionPerformed
        cursorActual = cursorPredeterminado;
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(true);
    }//GEN-LAST:event_jButtonBorrarTodoActionPerformed

    private void jButtonColorDeFondoPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorDeFondoPantallaActionPerformed
        colorObjeto = false;
        jDialogColor.setVisible(true);
        chkRelleno.setEnabled(true);
    }//GEN-LAST:event_jButtonColorDeFondoPantallaActionPerformed

    private void jToggleButtonColorObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonColorObjetosActionPerformed
        colorObjeto = true;
        jDialogColor.setVisible(true);
        chkRelleno.setEnabled(true);
    }//GEN-LAST:event_jToggleButtonColorObjetosActionPerformed

    private void chkRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRellenoActionPerformed
        if(chkRelleno.isSelected()){
            pantallaDibujo.setRelleno(true);
        }else{
            pantallaDibujo.setRelleno(false);
        }
}//GEN-LAST:event_chkRellenoActionPerformed

    private void jToggleButtonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRectanguloActionPerformed
        cursorActual = new Cursor(Cursor.CROSSHAIR_CURSOR);
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(true);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonRectanguloActionPerformed

    private void jToggleButtonTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTextoActionPerformed
        Cursor cursorLetra = new Cursor(Cursor.TEXT_CURSOR);
	cursorActual = cursorLetra;
        pantallaDibujo.setCursorActual(cursorActual);
        pantallaDibujo.setObjetoTexto(true);
        llamarObjetosDiferentes(evt);
        jPanelOpcionesObjeto.setVisible(false);
        chkRelleno.setEnabled(false);
    }//GEN-LAST:event_jToggleButtonTextoActionPerformed

    private void jButtonZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZoomInActionPerformed
        pantallaDibujo.acercar();
    }//GEN-LAST:event_jButtonZoomInActionPerformed

    private void jComboBoxGrosorBordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrosorBordeActionPerformed
        pantallaDibujo.setTamañoBorde(jComboBoxGrosorBorde.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxGrosorBordeActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseExited

    private void jToggleButtonrectanguloRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonrectanguloRedondoActionPerformed
        cursorActual = new Cursor(Cursor.CROSSHAIR_CURSOR);
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(true);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonrectanguloRedondoActionPerformed

    private void jToggleButtonCírculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCírculoActionPerformed
        cursorActual = new Cursor(Cursor.CROSSHAIR_CURSOR);
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(true);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonCírculoActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        imprimirPantallaDibujo();
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jMenuItemImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImprimirActionPerformed
        imprimirPantallaDibujo();
    }//GEN-LAST:event_jMenuItemImprimirActionPerformed

    private void jButtonDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeshacerActionPerformed
        llamarObjetosDiferentes(evt);
    }//GEN-LAST:event_jButtonDeshacerActionPerformed

    private void jButtonRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRehacerActionPerformed
        llamarObjetosDiferentes(evt);
    }//GEN-LAST:event_jButtonRehacerActionPerformed

    private void jButtonPantallaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPantallaCompletaActionPerformed
        if(soportaPantallaCompleta()){
            activarPantallaCompleta();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No soporta Pantalla Completa",
                Constantes.TITULO_PROGRAMA,
                JOptionPane.INFORMATION_MESSAGE);
            //pantallaDibujo.repaint();
        }
    }//GEN-LAST:event_jButtonPantallaCompletaActionPerformed

    private void jButtonZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZoomOutActionPerformed
        pantallaDibujo.alejar();
    }//GEN-LAST:event_jButtonZoomOutActionPerformed

    private void jMenuItemZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZoomOutActionPerformed
        pantallaDibujo.alejar();
}//GEN-LAST:event_jMenuItemZoomOutActionPerformed

    private void jMenuItemZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZoomInActionPerformed
        pantallaDibujo.acercar();
}//GEN-LAST:event_jMenuItemZoomInActionPerformed

    private void jMenuItemRehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRehacerActionPerformed
        llamarObjetosDiferentes(evt);
}//GEN-LAST:event_jMenuItemRehacerActionPerformed

    private void jMenuItemDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeshacerActionPerformed
        llamarObjetosDiferentes(evt);
}//GEN-LAST:event_jMenuItemDeshacerActionPerformed

    private void jToggleButtonPincelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPincelActionPerformed
        Cursor cursorPincel = toolKit.createCustomCursor(brushImg,new Point(3, 23),"Brush Cursor");
	cursorActual = cursorPincel;
        pantallaDibujo.setTamañoBorde(jComboBoxGrosorBorde.getSelectedIndex());
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(false);
        jPanelOpcionesObjeto.setVisible(true);
    }//GEN-LAST:event_jToggleButtonPincelActionPerformed

    private void jToggleButtonBorrarIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBorrarIndividualActionPerformed
        Cursor cursorBorrador = toolKit.createCustomCursor(eraserImg,new Point(15,15),"Eraser Cursor");
        cursorActual = cursorBorrador;
        pantallaDibujo.setCursorActual(cursorActual);
        llamarObjetosDiferentes(evt);
        chkRelleno.setEnabled(false);
        jPanelOpcionesObjeto.setVisible(false);
    }//GEN-LAST:event_jToggleButtonBorrarIndividualActionPerformed

    private void jButtonDesactivarPantallaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesactivarPantallaCompletaActionPerformed
        desactivarPantallaCompleta();
    }//GEN-LAST:event_jButtonDesactivarPantallaCompletaActionPerformed

    public void llamarObjetosDiferentes(ActionEvent event){
        if(event.getSource() == jToggleButtonLinea){
            pantallaDibujo.setDrawMode(pantallaDibujo.getLINE());
            jLabelHerramientaSeleccionadaObjeto.setText("Linea");
        }
        if(event.getSource() == jToggleButtonRectangulo){
            pantallaDibujo.setDrawMode(pantallaDibujo.getSQUARE());
            jLabelHerramientaSeleccionadaObjeto.setText("Rectangulo");
        }
        if(event.getSource() == jToggleButtonOvalo){
            pantallaDibujo.setDrawMode(pantallaDibujo.getOVAL());
            jLabelHerramientaSeleccionadaObjeto.setText("Ovalo");
        }
         if(event.getSource() == jToggleButtonCírculo){
            pantallaDibujo.setDrawMode(pantallaDibujo.getCIRCULO());
            jLabelHerramientaSeleccionadaObjeto.setText("Circulo");
        }
        if(event.getSource() == jToggleButtonrectanguloRedondo){
            pantallaDibujo.setDrawMode(pantallaDibujo.getROUND_RECT());
            jLabelHerramientaSeleccionadaObjeto.setText("Rectangulo Redondo");
        }
        if(event.getSource() == jToggleButtonLapiz){
            pantallaDibujo.setDrawMode(pantallaDibujo.getFREE_HAND());
            jLabelHerramientaSeleccionadaObjeto.setText("Lápiz");
        }
        if(event.getSource() == jToggleButtonPincel){
            pantallaDibujo.setDrawMode(pantallaDibujo.getFREE_HAND());
            jLabelHerramientaSeleccionadaObjeto.setText("Pincel");
        }
        if(event.getSource() == jButtonDeshacer || event.getSource() == jMenuItemDeshacer){
            pantallaDibujo.deshacer();
        }
        if(event.getSource() == jButtonRehacer || event.getSource() == jMenuItemRehacer){
            pantallaDibujo.rehacer();
        }
        if(event.getSource() == jButtonBorrarTodo){
            pantallaDibujo.borrarTodo();
            jLabelHerramientaSeleccionadaObjeto.setText("Borrar Todo");
        }
        if (event.getSource() == jToggleButtonBorrarIndividual){
            jLabelHerramientaSeleccionadaObjeto.setText("Borrador");
            pantallaDibujo.setDrawMode(60);
        }
        if (event.getSource() == jToggleButtonTexto){
            jLabelHerramientaSeleccionadaObjeto.setText("Texto");
            //pantallaDibujo.setDrawMode(72);
        }
    }

    // Metodo que muestra la ventana Ayuda
    public void mostrarVentanaAyuda() {
        if (ventanaAyuda == null) {
            ventanaAyuda = new VentanaAyuda(this, rootPaneCheckingEnabled);
            ventanaAyuda.setLocationRelativeTo(this);
        }
        ventanaAyuda.setVisible(rootPaneCheckingEnabled);
    }

    // Metodo que imprime lo que esta en la pantallaDibujo
    public void imprimirPantallaDibujo() {
        PrinterJob printJob = PrinterJob.getPrinterJob();
        printJob.setPrintable( pantallaDibujo);

        // Dialogo de configuracion de paginas
        PageFormat pf = printJob.pageDialog( printJob.defaultPage() );


        // Dialogo de configuracion de impresora
        if( printJob.printDialog() ) {
            try {
                printJob.print();
            } catch(java.awt.print.PrinterException e){
                System.out.println("El servicio de impresion esta desactivado.");
            }
            catch( Exception e ) {
                e.printStackTrace();
            }
        }
    }

    // Comprobar si tiene soporte a pantalla completa
    public boolean soportaPantallaCompleta(){
        return gd.isFullScreenSupported();
    }

    // Activamos el modo a pantalla completa
    public void activarPantallaCompleta(){
        gd.setFullScreenWindow(this);
        jButtonPantallaCompleta.setVisible(false);
        jButtonDesactivarPantallaCompleta.setVisible(true);
    }


    // desactivamos el modo a pantalla completa
    public void desactivarPantallaCompleta(){
       gd.setFullScreenWindow(null);
       jButtonPantallaCompleta.setVisible(true);
       jButtonDesactivarPantallaCompleta.setVisible(false);
    }

    



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupObjetos;
    private javax.swing.JCheckBox chkRelleno;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JToggleButton jButtonBorrarTodo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JToggleButton jButtonColorDeFondoPantalla;
    private javax.swing.JButton jButtonDesactivarPantallaCompleta;
    private javax.swing.JButton jButtonDeshacer;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonPantallaCompleta;
    private javax.swing.JButton jButtonRehacer;
    private javax.swing.JButton jButtonZoomIn;
    private javax.swing.JButton jButtonZoomOut;
    private javax.swing.JColorChooser jColorChooserColores;
    private javax.swing.JComboBox jComboBoxGrosorBorde;
    private javax.swing.JDialog jDialogColor;
    public static javax.swing.JLabel jLabelCoordenadasPuntero;
    private javax.swing.JLabel jLabelHerramientaSeleccionada;
    private javax.swing.JLabel jLabelHerramientaSeleccionadaObjeto;
    private javax.swing.JLabel jLabelTamañoGrosor;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemDeshacer;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemGuardarComo;
    private javax.swing.JMenuItem jMenuItemImprimir;
    private javax.swing.JMenuItem jMenuItemIndice;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemRehacer;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemZoomIn;
    private javax.swing.JMenuItem jMenuItemZoomOut;
    private javax.swing.JPanel jPanelAccesoDirecto;
    private javax.swing.JPanel jPanelBarraDeHerramientas;
    private javax.swing.JPanel jPanelBarraHerramientasTotal;
    private javax.swing.JPanel jPanelDerechoVacio;
    private javax.swing.JPanel jPanelInformacionExtra;
    private javax.swing.JPanel jPanelOpcionesObjeto;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    public static javax.swing.JToggleButton jToggleButtonBorrarIndividual;
    private javax.swing.JToggleButton jToggleButtonColorObjetos;
    private javax.swing.JToggleButton jToggleButtonCírculo;
    private javax.swing.JToggleButton jToggleButtonLapiz;
    private javax.swing.JToggleButton jToggleButtonLinea;
    private javax.swing.JToggleButton jToggleButtonOvalo;
    private javax.swing.JToggleButton jToggleButtonPincel;
    private javax.swing.JToggleButton jToggleButtonRectangulo;
    public static javax.swing.JToggleButton jToggleButtonTexto;
    private javax.swing.JToggleButton jToggleButtonrectanguloRedondo;
    private javax.swing.JToolBar jToolBarBarraDeHerramientas;
    // End of variables declaration//GEN-END:variables
}