/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author proyectosbeta
 */
public class panelDibujoTexto extends javax.swing.JPanel {
    // Objetos.
    private BufferedImage imagen;
    private static String rutaImagenTemporal;
    
    /**
     * Creates new form panelDibujoTexto
     */
    public panelDibujoTexto(String rutaImagenTemporal) {
        /*
         * Se guarda la ruta de la imagen temporal para luego usar,
         * al crear un Texto con registros de la base de datos.
         */
        this.rutaImagenTemporal = rutaImagenTemporal;
        
        initComponents();
        
        try{         
            System.out.println("El archivo temporal de la imagen es:  " + rutaImagenTemporal);
            imagen = ImageIO.read(new File(rutaImagenTemporal));
            int height = imagen.getHeight(this);
            int width = imagen.getWidth(this);
            setPreferredSize(new Dimension(width, height));
        }catch(IOException ex){
            // handle exception...
            System.out.println("Problemas imagen");
       }
    }
    
    @Override
    public void paint(Graphics g) {
        System.out.println("entro al paint");
        super.paint(g);
        g.drawImage(imagen, 0, 0, null);           
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Red Rock");
        //frame.add(new panelDibujoTexto());

        frame.setContentPane(new panelDibujoTexto(rutaImagenTemporal));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
