/*
 * VentanaTexto.java
 *
 * Created on 05/09/2010, 09:51:37 PM
 */

package GUI;

import Auxiliar.Constantes;
import Auxiliar.Texto;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author gaby
 */
public class VentanaTexto extends javax.swing.JDialog {
     // Obtenemos la referencia al entorno de ventanas
    private GraphicsEnvironment gEnv;

    // Variables
    private String tipoFuentePredeterminada = "Dialog";
    private Texto texto;
    private boolean dibujaTexto;
    private VentanaColor ventanaColor;

    /** Creates new form VentanaTexto */
    public VentanaTexto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e){}
        gEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        initComponents();
        texto = null;
        ventanaColor = null;
        dibujaTexto = false;
        this.setTitle("Introduzca un texto");   // titulo de la ventana
        this.setResizable(false);               // No redimensiona la ventana
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTextPanel = new javax.swing.JPanel();
        jLabelIntroduzcaTexto = new javax.swing.JLabel();
        jTextFieldTexto = new javax.swing.JTextField();
        jPanelOpcionesTexto = new javax.swing.JPanel();
        jLabelTipolFuente = new javax.swing.JLabel();
        jComboBoxTipoFuentes = new javax.swing.JComboBox(gEnv.getAvailableFontFamilyNames());
        jLabelEstilo = new javax.swing.JLabel();
        jComboBoxTipoEstilo = new javax.swing.JComboBox();
        jLabelTamañoTexto = new javax.swing.JLabel();
        jSpinnerTamañoTexto = new javax.swing.JSpinner(new SpinnerNumberModel(Constantes.VALOR_PREDETERMINADO_SPINNER_NUMBER_MODEL, Constantes.VALOR_MINIMO_SPINNER_NUMBER_MODEL, Constantes.VALOR_MAXIMO_SPINNER_NUMBER_MODEL, Constantes.INCREMENTO_SPINNER_NUMBER_MODEL));
        jPanelConfirmacion = new javax.swing.JPanel();
        jButtonColor = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIntroduzcaTexto.setText("Introduzca un texto:");

        javax.swing.GroupLayout jPanelTextPanelLayout = new javax.swing.GroupLayout(jPanelTextPanel);
        jPanelTextPanel.setLayout(jPanelTextPanelLayout);
        jPanelTextPanelLayout.setHorizontalGroup(
            jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIntroduzcaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTextPanelLayout.setVerticalGroup(
            jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIntroduzcaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextFieldTexto)))
        );

        jLabelTipolFuente.setText("Fuentes:");
        jLabelTipolFuente.setToolTipText("Tipo de Fuentes");

        jComboBoxTipoFuentes.setMaximumRowCount(5);
        jComboBoxTipoFuentes.setSelectedItem(tipoFuentePredeterminada);
        jComboBoxTipoFuentes.setToolTipText("Tipos de Fuente");
        jComboBoxTipoFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoFuentesActionPerformed(evt);
            }
        });

        jLabelEstilo.setText("Estilo:");

        jComboBoxTipoEstilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Negrita", "Cursiva", "Negrita Cursiva" }));
        jComboBoxTipoEstilo.setToolTipText("Tipo de Estilos");

        jLabelTamañoTexto.setText("Tamaño:");

        jSpinnerTamañoTexto.setToolTipText("Tamaño");

        jButtonColor.setText("Color");
        jButtonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfirmacionLayout = new javax.swing.GroupLayout(jPanelConfirmacion);
        jPanelConfirmacion.setLayout(jPanelConfirmacionLayout);
        jPanelConfirmacionLayout.setHorizontalGroup(
            jPanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonColor)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanelConfirmacionLayout.setVerticalGroup(
            jPanelConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfirmacionLayout.createSequentialGroup()
                .addComponent(jButtonColor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesTextoLayout = new javax.swing.GroupLayout(jPanelOpcionesTexto);
        jPanelOpcionesTexto.setLayout(jPanelOpcionesTextoLayout);
        jPanelOpcionesTextoLayout.setHorizontalGroup(
            jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipolFuente, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxTipoFuentes, 0, 52, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jLabelEstilo)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxTipoEstilo, 0, 95, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jLabelTamañoTexto)
                .addGap(5, 5, 5)
                .addComponent(jSpinnerTamañoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addComponent(jPanelConfirmacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionesTextoLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(31, 31, 31)
                .addComponent(jButtonCancelar)
                .addGap(96, 96, 96))
        );
        jPanelOpcionesTextoLayout.setVerticalGroup(
            jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                .addGroup(jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTipolFuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jComboBoxTipoFuentes)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelEstilo))
                    .addComponent(jComboBoxTipoEstilo)
                    .addGroup(jPanelOpcionesTextoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTamañoTexto))
                    .addComponent(jSpinnerTamañoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcionesTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOpcionesTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOpcionesTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoFuentesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxTipoFuentesActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(!jTextFieldTexto.getText().equals("")){
            int numeroEntero = Integer.parseInt(jSpinnerTamañoTexto.getValue().toString());
            Color colorTexto;
            if(ventanaColor != null){
                colorTexto = ventanaColor.getJColorChooserColores().getColor();
            }else{
                colorTexto = Color.BLACK; // color negro predeterminado
            }
                
            texto = new Texto(jTextFieldTexto.getText(), jComboBoxTipoFuentes.getSelectedIndex(),
                jComboBoxTipoEstilo.getSelectedIndex(), numeroEntero, colorTexto);
            this.setVisible(false);
            setDibujaTexto(true);
          //repaint();
        }else {
            String mensaje = "Introdusca un texto!!!";
            JOptionPane.showMessageDialog(this, mensaje, Constantes.TITULO_PROGRAMA,
                JOptionPane.PLAIN_MESSAGE);
            repaint();
        }
}//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
        dispose();
        //repaint();
        setDibujaTexto(false);
}//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorActionPerformed
        mostrarVentanaColor();
        // Centrar el ventana Color
        ventanaColor.setLocationRelativeTo(this);

        //texto.setColor(Color.BLACK);
        ventanaColor.getJColorChooserColores().setColor(texto.getColor());
        ventanaColor.setTitle("Color del texto");
    }//GEN-LAST:event_jButtonColorActionPerformed

    // Metodos get y set
    public Texto getTexto() {
        return texto;
    }

    public void setTexto(Texto texto) {
        this.texto = texto;
    }

    public boolean isDibujaTexto() {
        return dibujaTexto;
    }

    public void setDibujaTexto(boolean dibujaTexto) {
        this.dibujaTexto = dibujaTexto;
    }

    // Metodo que muestra la ventana Color
    public void mostrarVentanaColor() {
        if (ventanaColor == null) {
            ventanaColor = new VentanaColor(null, rootPaneCheckingEnabled);
            ventanaColor.setLocationRelativeTo(this);
        }
        ventanaColor.setVisible(true);
    }




    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaTexto dialog = new VentanaTexto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonColor;
    private javax.swing.JComboBox jComboBoxTipoEstilo;
    private javax.swing.JComboBox jComboBoxTipoFuentes;
    private javax.swing.JLabel jLabelEstilo;
    private javax.swing.JLabel jLabelIntroduzcaTexto;
    private javax.swing.JLabel jLabelTamañoTexto;
    private javax.swing.JLabel jLabelTipolFuente;
    private javax.swing.JPanel jPanelConfirmacion;
    private javax.swing.JPanel jPanelOpcionesTexto;
    private javax.swing.JPanel jPanelTextPanel;
    private javax.swing.JSpinner jSpinnerTamañoTexto;
    private javax.swing.JTextField jTextFieldTexto;
    // End of variables declaration//GEN-END:variables

}
